server:
  servlet:
    context-path: "/api"

logging:
  level:
    org.springframework.security.web: DEBUG
mongodb:
  uri: mongodb+srv://<username>:<password>@<clusterid>.mongodb.net/?retryWrites=true&w=majority
  database: "speer-assignment"

JWTConfig:
  EXPIRY: 86400000 #24 Hours
  SECRET: "veryveryuniversalmostsecuredsecretforspeerassignment"

rate_limit_per_minute: 10